### ISSUE TITLE
New package name

### ISSUE THREAD

**Issue by lionel-** [lionel-/tidyselect#2]
Because `selectr` is already a CRAN package. Is `tidysel` reasonable @hadley?

**Comment by hadley** [comment]
How about tidyselect? I think it can be long since it'll mostly be used by other package

**Comment by lionel-** [comment]
It can be long but shorter is still better, especially since that's the kind of packages that you don't import from but call functions namespace-qualified. I think I prefer tidysel, which one do you prefer?

**Comment by hadley** [comment]
I definitely prefer tidyselect
